export const CountryTraslation = {
  'Netherlands' : 'Paises Bajos',
  'Wales' : 'Gales',
  'England' : 'Inglaterra',
  'Saudi Arabia' : 'Arabia Saudi',
  'Denmark' : 'Dinamarca',
  'Tunisia': 'Tunez',
  'Poland': 'Polonia',
  'France': 'Francia',
  'Morocco': 'Marruecos',
  'Croatia': 'Croacia',
  'Germany': 'Alemania',
  'Japan': 'Japon',
  'Belgium': 'Belgica',
  'Spain': 'España',
  'Switzerland': 'Suiza',
  'Cameroon': 'Camerun',
  'South Korea': 'Korea Del Sur',
}